[project]
name = "dgp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets",
    "fasttext-wheel",
    "groq>=0.37.0",
    "langgraph",
    "openai",
    "sacrebleu",
    "transformers",
    "accelerate",
    "unbabel-comet",
    "google-genai",
    "pillow",
]
